# Generated by Django 3.2.6 on 2021-08-27 08:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spendings', '0002_auto_20210826_1932'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spending',
            unique_together={('category', 'user')},
        ),
    ]
