# Generated by Django 3.2.6 on 2021-08-27 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spendings', '0006_alter_spendingcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendingcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='spendingcategory',
            unique_together={('user', 'name')},
        ),
    ]
