POST http://127.0.0.1:8000/v1/auth/
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "test"
}

###

GET http://127.0.0.1:8000/v1/profile/
Content-Type: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI5Mzc0NjYyLCJqdGkiOiJkYzhhYTgxMjM1MDE0MDQ3YWNiNzUyZTcwNDY0OWM5NSIsInVzZXJfaWQiOjF9.AMILlpwfTGG3JUeo86a6Sq3midVp_BFXYEr7AfXD1rg

###
